# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: hkks/benchmarksoft:0.1.4

stages:
  - build
  - deploy
  - test
  - performance

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - cd build
    - pwd
    - cmake ..
    - make
    - ../bin64/BenchmarkSoft

# run tests using the binary built before
deploy:
  stage: deploy
  script:
    - pwd
    - ls /builds/sreekumar/BenchmarkSoft/bin64
    - ls /builds/sreekumar/BenchmarkSoft/build

# run tests using the binary built before
test:
  stage: test
  script:
    - pwd
    - ls /builds/sreekumar/BenchmarkSoft/bin64
    - ls /builds/sreekumar/BenchmarkSoft/build
#    - ./bin64/BenchmarkSoft

performance:
  stage: performance
  script:
    - pwd
    - ls /builds/sreekumar/BenchmarkSoft/bin64
    - ls /builds/sreekumar/BenchmarkSoft/build
#    - ./bin64/BenchmarkSoft
